# Generated by Django 4.2 on 2024-12-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_booking_app', '0003_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
